### ISSUE TITLE
과제 제출합니다.

### ISSUE THREAD

**Issue by Nodept** [campus-devil1032/campus-week1-repo#8]
https://github.com/campus-devil1032/campus-week1-repo/blob/407e9ded2996ec5d9972dfbad790c0b98981d20a/exam.html#L9

여기 CSS부분 더 개선할 방향이 있을까요?

**Comment by campus-devil1032** [comment]
스타일 시트는 내부로 관리하는 것보다 외부 파일로 관리 하는 걸 추천드립니다 :) 
재사용성이 올라가고 가독성이 좋아져요!
